"Filed out from Dolphin Smalltalk 7"!

PackageManifest subclass: #ManifestMaterialDesignLiteWidgetsTests
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ManifestMaterialDesignLiteWidgetsTests guid: (GUID fromString: '{07531df4-8f1c-4181-91b9-a688233f40e1}')!
ManifestMaterialDesignLiteWidgetsTests comment: 'ManifestMaterialDesignLiteWidgetsTests class	instanceVariableNames: '''''!
!ManifestMaterialDesignLiteWidgetsTests categoriesForClass!Material-Design-Lite-Widgets-Tests-Manifest! !
!ManifestMaterialDesignLiteWidgetsTests class methodsFor!

ruleRBMissingTranslationsInMenusRuleV1FalsePositive	^ #(#(#(#RGMethodDefinition #(#MDLDialogWidgetTests #testTitle #false)) #'2018-07-10T12:50:37.968201+02:00') )! !
!ManifestMaterialDesignLiteWidgetsTests class categoriesFor: #ruleRBMissingTranslationsInMenusRuleV1FalsePositive!code/critics!public! !

