"Filed out from Dolphin Smalltalk 7"!

PackageManifest subclass: #ManifestMaterialDesignLiteComponentsTests
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ManifestMaterialDesignLiteComponentsTests guid: (GUID fromString: '{03b45e2a-96ae-4c9f-a9ec-f0056cecdffc}')!
ManifestMaterialDesignLiteComponentsTests comment: 'ManifestMaterialDesignLiteComponentsTests class	instanceVariableNames: '''''!
!ManifestMaterialDesignLiteComponentsTests categoriesForClass!Material-Design-Lite-Components-Tests-Manifest! !
!ManifestMaterialDesignLiteComponentsTests class methodsFor!

ruleRBRefersToClassRuleV1FalsePositive	^ #(#(#(#RGMethodDefinition #(#'MDLAbstractBrushTest class' #isAbstract #true)) #'2018-05-17T02:23:38.212953+02:00') #(#(#RGMethodDefinition #(#'MDLCardInnerDivTest class' #isAbstract #true)) #'2018-05-17T16:46:08.979953+02:00') )! !
!ManifestMaterialDesignLiteComponentsTests class categoriesFor: #ruleRBRefersToClassRuleV1FalsePositive!code/critics!public! !

