"Filed out from Dolphin Smalltalk 7"!

PackageManifest subclass: #ManifestMaterialDesignColors
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ManifestMaterialDesignColors guid: (GUID fromString: '{8aa87489-d665-450b-afe0-4be994bfdb56}')!
ManifestMaterialDesignColors comment: 'ManifestMaterialDesignColors class	instanceVariableNames: '''''!
!ManifestMaterialDesignColors categoriesForClass!Material-Design-Colors! !
!ManifestMaterialDesignColors class methodsFor!

description ^ 'I am a package containing extensions to the Pharo colors following Material Design recommendations. For more info see:https://material.io/guidelines/style/color.html'! !
!ManifestMaterialDesignColors class categoriesFor: #description!meta/data!public! !

