"Filed out from Dolphin Smalltalk 7"!

MDLLinkingLayoutSection subclass: #MDLAbstractHeaderSection
	instanceVariableNames: 'brush'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLAbstractHeaderSection guid: (GUID fromString: '{6abddec2-ca7b-4465-a9ae-c6f349d26f51}')!
MDLAbstractHeaderSection comment: ''!
!MDLAbstractHeaderSection categoriesForClass!Material-Design-Lite-Widgets-Header! !
!MDLAbstractHeaderSection methodsFor!

initialize	super initialize.	brush := MDLLayoutHeader new! !
!MDLAbstractHeaderSection categoriesFor: #initialize!initialization!public! !

