"Filed out from Dolphin Smalltalk 7"!

MDLAbstractSeasideTestCase subclass: #MDLAbstractBrushTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLAbstractBrushTest guid: (GUID fromString: '{a0770957-edd0-42b4-8b3c-2afaab074919}')!
MDLAbstractBrushTest comment: ''!
!MDLAbstractBrushTest categoriesForClass!Material-Design-Lite-Components-Tests-Abstract! !
!MDLAbstractBrushTest methodsFor!

testBareBrush	self subclassResponsibility!

testWithContent	self subclassResponsibility! !
!MDLAbstractBrushTest categoriesFor: #testBareBrush!public!tests! !
!MDLAbstractBrushTest categoriesFor: #testWithContent!public!tests! !

!MDLAbstractBrushTest class methodsFor!

isAbstract	^ self = MDLAbstractBrushTest! !
!MDLAbstractBrushTest class categoriesFor: #isAbstract!public!testing! !

