"Filed out from Dolphin Smalltalk 7"!

MDLAbstractFilter subclass: #MDLBeginsWithFilter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLBeginsWithFilter guid: (GUID fromString: '{cd026101-32eb-4213-8f8f-00337adc51af}')!
MDLBeginsWithFilter comment: 'MDLBeginsWithFilter class	instanceVariableNames: '''''!
!MDLBeginsWithFilter categoriesForClass!Material-Design-Lite-Widgets-List! !
!MDLBeginsWithFilter class methodsFor!

formatedElement: aString matches: aPattern	^ aString beginsWith: aPattern! !
!MDLBeginsWithFilter class categoriesFor: #formatedElement:matches:!accessing!public! !

