"Filed out from Dolphin Smalltalk 7"!

WATagBrush subclass: #MDLChipTextTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLChipTextTag guid: (GUID fromString: '{e6f65e64-b3a4-4357-bf93-ca1f775f7f18}')!
MDLChipTextTag comment: 'Description--------------------I am just some text inside a MDLChip.'!
!MDLChipTextTag categoriesForClass!Material-Design-Lite-Components-Chips! !
!MDLChipTextTag methodsFor!

initialize	super initialize.	self class: #'mdl-chip__text'!

tag	^ 'span'! !
!MDLChipTextTag categoriesFor: #initialize!initialization!public! !
!MDLChipTextTag categoriesFor: #tag!accessing!public! !

