"Filed out from Dolphin Smalltalk 7"!

MDLCardInnerDiv subclass: #MDLCardMedia
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLCardMedia guid: (GUID fromString: '{10355c51-b395-43ef-8d0a-96a57a203da9}')!
MDLCardMedia comment: 'Description--------------------I am a brush to create a medias in a card.'!
!MDLCardMedia categoriesForClass!Material-Design-Lite-Components-Cards! !
!MDLCardMedia methodsFor!

initialize	super initialize.	self class: 'mdl-card__media'! !
!MDLCardMedia categoriesFor: #initialize!initialization!public! !

