"Filed out from Dolphin Smalltalk 7"!

WACheckboxTag subclass: #MDLCheckbox
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLCheckbox guid: (GUID fromString: '{c0772108-95b9-4de7-b7b5-b32b6d4d0fdc}')!
MDLCheckbox comment: 'Description--------------------I am a brush to create MDL chekboxes.Example--------------------	html mdlCheckboxContainer		rippleEffect;		for: html nextId;		with: [ html mdlCheckbox				value: true;				id: html lastId.			html mdlCheckboxLabel: ''Checkbox'' ]'!
!MDLCheckbox categoriesForClass!Material-Design-Lite-Components-Forms! !
!MDLCheckbox methodsFor!

initialize	super initialize.	self class: 'mdl-checkbox__input'! !
!MDLCheckbox categoriesFor: #initialize!initialization!public! !

