"Filed out from Dolphin Smalltalk 7"!

MDLAbstractBrushTest subclass: #MDLCardInnerDivTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLCardInnerDivTest guid: (GUID fromString: '{36926830-ea73-4777-9d60-2a536b849b92}')!
MDLCardInnerDivTest comment: 'A MDLCardInnerDivTest is a test class for testing the behavior of MDLCardInnerDiv'!
!MDLCardInnerDivTest categoriesForClass!Material-Design-Lite-Components-Tests-Card! !
!MDLCardInnerDivTest methodsFor!

testBorder	self subclassResponsibility!

testExpand	self subclassResponsibility! !
!MDLCardInnerDivTest categoriesFor: #testBorder!public!tests! !
!MDLCardInnerDivTest categoriesFor: #testExpand!public!tests! !

!MDLCardInnerDivTest class methodsFor!

isAbstract	^ self = MDLCardInnerDivTest! !
!MDLCardInnerDivTest class categoriesFor: #isAbstract!public!testing! !

