"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLCardInnerDiv
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLCardInnerDiv guid: (GUID fromString: '{60a075fe-ab58-4ba0-9bfd-f284b2e22978}')!
MDLCardInnerDiv comment: 'Description--------------------I''m a Card inner div. Place me or my subclasses into a Card.'!
!MDLCardInnerDiv categoriesForClass!Material-Design-Lite-Components-Cards! !
!MDLCardInnerDiv methodsFor!

border	self class: 'mdl-card--border'!

expand	self class: 'mdl-card--expand'! !
!MDLCardInnerDiv categoriesFor: #border!options!public! !
!MDLCardInnerDiv categoriesFor: #expand!options!public! !

