"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLCardSubtitleText
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLCardSubtitleText guid: (GUID fromString: '{aef1ef8c-df51-4ae3-ba5a-17cbcc9a8e21}')!
MDLCardSubtitleText comment: 'Description--------------------I am a brush to create a subtitle to a card.'!
!MDLCardSubtitleText categoriesForClass!Material-Design-Lite-Components-Cards! !
!MDLCardSubtitleText methodsFor!

initialize	super initialize.	self class: 'mdl-card__subtitle-text'! !
!MDLCardSubtitleText categoriesFor: #initialize!initialization!public! !

