"Filed out from Dolphin Smalltalk 7"!

MDLDemoScreen subclass: #MDLComponentDemo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLComponentDemo guid: (GUID fromString: '{0b1ac596-bb78-450a-a0e2-e1f6fe3a3216}')!
MDLComponentDemo comment: 'MDLComponentDemo subclass: #MDLAnchorButtonsScreen	instanceVariableNames: ''''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Material-Design-Lite-Demo-Components'''!
!MDLComponentDemo categoriesForClass!Material-Design-Lite-Demo-Components! !
