"Filed out from Dolphin Smalltalk 7"!

MDLDemoScreen subclass: #MDLComponentDemo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLComponentDemo guid: (GUID fromString: '{0b1ac596-bb78-450a-a0e2-e1f6fe3a3216}')!
MDLComponentDemo comment: 'MDLComponentDemo class	instanceVariableNames: '''''!
!MDLComponentDemo categoriesForClass!Material-Design-Lite-Demo-Components! !
!MDLComponentDemo class methodsFor!

isAbstract	^ self = MDLComponentDemo! !
!MDLComponentDemo class categoriesFor: #isAbstract!public!testing! !

