"Filed out from Dolphin Smalltalk 7"!

WATagBrush subclass: #MDLDivTag
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLDivTag guid: (GUID fromString: '{c84e0e39-ac21-44a1-954b-d2df630fdaa4}')!
MDLDivTag comment: 'Description--------------------The <div> tag defines a division/section in a document.Use the <div> tag to group block-elements to format them with styles.'!
!MDLDivTag categoriesForClass!Material-Design-Lite-Components-Core! !
!MDLDivTag methodsFor!

tag	^ 'div'! !
!MDLDivTag categoriesFor: #tag!accessing!public! !

