"Filed out from Dolphin Smalltalk 7"!

WAComponent subclass: #MDLDialogWidgetSimpleWidgetMock
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLDialogWidgetSimpleWidgetMock guid: (GUID fromString: '{aff7655f-ae58-4baf-a556-c8782ab8a821}')!
MDLDialogWidgetSimpleWidgetMock comment: ''!
!MDLDialogWidgetSimpleWidgetMock categoriesForClass!Material-Design-Lite-Widgets-Tests-Dialog! !
!MDLDialogWidgetSimpleWidgetMock methodsFor!

renderContentOn: html	html text: 'This is a mock'! !
!MDLDialogWidgetSimpleWidgetMock categoriesFor: #renderContentOn:!public!rendering! !

