"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLExpansionPanelHeaderTitle
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLExpansionPanelHeaderTitle guid: (GUID fromString: '{39c23811-6019-4cd6-a6df-fe1621262c68}')!
MDLExpansionPanelHeaderTitle comment: 'Description--------------------I am a brush to create the title for a MDL Expansion Panels Header.'!
!MDLExpansionPanelHeaderTitle categoriesForClass!Material-Design-Lite-Components-ExpansionPanels! !
!MDLExpansionPanelHeaderTitle methodsFor!

initialize	super initialize.	self class: 'mdl-expansion-panel__header-title'! !
!MDLExpansionPanelHeaderTitle categoriesFor: #initialize!initialization!public! !

