"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLExpansionPanelHeaderDescription
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLExpansionPanelHeaderDescription guid: (GUID fromString: '{8ebcc60b-7e1b-4aba-8e7e-70e1669cf483}')!
MDLExpansionPanelHeaderDescription comment: 'Description--------------------I am a brush to create the description for a MDL Expansion Panel Header.'!
!MDLExpansionPanelHeaderDescription categoriesForClass!Material-Design-Lite-Components-ExpansionPanels! !
!MDLExpansionPanelHeaderDescription methodsFor!

initialize	super initialize.	self class: 'mdl-expansion-panel__header-description'! !
!MDLExpansionPanelHeaderDescription categoriesFor: #initialize!initialization!public! !

