"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLExpansionPanelContent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLExpansionPanelContent guid: (GUID fromString: '{65ef2ca5-d9c7-43d6-a17b-588040387576}')!
MDLExpansionPanelContent comment: 'Description--------------------I am a brush to create the content for a MDL Expansion Panel.'!
!MDLExpansionPanelContent categoriesForClass!Material-Design-Lite-Components-ExpansionPanels! !
!MDLExpansionPanelContent methodsFor!

initialize	super initialize.	self class: 'mdl-expansion-panel__content'! !
!MDLExpansionPanelContent categoriesFor: #initialize!initialization!public! !

