"Filed out from Dolphin Smalltalk 7"!

WAComponent subclass: #MDLExampleRightPanel2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLExampleRightPanel2 guid: (GUID fromString: '{79bd98f1-ed68-42b1-985b-84ace97d3f67}')!
MDLExampleRightPanel2 comment: 'Description--------------------Utility component to illustrate the right panel extension.'!
!MDLExampleRightPanel2 categoriesForClass!Material-Design-Lite-Demo-Utils! !
!MDLExampleRightPanel2 methodsFor!

renderContentOn: html	html render: 'This is the second panel'! !
!MDLExampleRightPanel2 categoriesFor: #renderContentOn:!public!rendering! !

