"Filed out from Dolphin Smalltalk 7"!

MDLDemoScreen subclass: #MDLExtensionsDemo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLExtensionsDemo guid: (GUID fromString: '{c65aa0ce-a177-4fd8-9d16-6d16e18893e9}')!
MDLExtensionsDemo comment: 'MDLExtensionsDemo class	instanceVariableNames: '''''!
!MDLExtensionsDemo categoriesForClass!Material-Design-Lite-Demo-Extensions! !
!MDLExtensionsDemo class methodsFor!

isAbstract	^ self = MDLExtensionsDemo! !
!MDLExtensionsDemo class categoriesFor: #isAbstract!public!testing! !

