"Filed out from Dolphin Smalltalk 7"!

WAComponent subclass: #MDLExampleRightPanel1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLExampleRightPanel1 guid: (GUID fromString: '{96b448bd-57d1-4bd4-a7b7-36c5b702afbb}')!
MDLExampleRightPanel1 comment: 'Description--------------------Utility component to illustrate the right panel extension.'!
!MDLExampleRightPanel1 categoriesForClass!Material-Design-Lite-Demo-Utils! !
!MDLExampleRightPanel1 methodsFor!

renderContentOn: html	html render: 'This is the first panel'! !
!MDLExampleRightPanel1 categoriesFor: #renderContentOn:!public!rendering! !

