"Filed out from Dolphin Smalltalk 7"!

MDLFooterAbstractSection subclass: #MDLFooterNilSection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLFooterNilSection guid: (GUID fromString: '{3e43b1a4-c184-4f0c-8fe4-cf21b496b44e}')!
MDLFooterNilSection comment: ''!
!MDLFooterNilSection categoriesForClass!Material-Design-Lite-Widgets-Footer! !
!MDLFooterNilSection methodsFor!

addLinks: someLinks	self shouldNotImplement !

isNilSection	^ true!

renderSectionOn: html	"do nothing"! !
!MDLFooterNilSection categoriesFor: #addLinks:!adding!public! !
!MDLFooterNilSection categoriesFor: #isNilSection!public!testing! !
!MDLFooterNilSection categoriesFor: #renderSectionOn:!public!testing! !

