"Filed out from Dolphin Smalltalk 7"!

Object subclass: #MDLFooterAbstractSection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLFooterAbstractSection guid: (GUID fromString: '{74f7dd52-8fed-4507-8e9a-9aadf94d280f}')!
MDLFooterAbstractSection comment: ''!
!MDLFooterAbstractSection categoriesForClass!Material-Design-Lite-Widgets-Footer! !
!MDLFooterAbstractSection methodsFor!

isNilSection	^ false!

renderSectionOn: html	self subclassResponsibility ! !
!MDLFooterAbstractSection categoriesFor: #isNilSection!public!testing! !
!MDLFooterAbstractSection categoriesFor: #renderSectionOn:!public!rendering! !

