"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLLogo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLLogo guid: (GUID fromString: '{0c823d98-be63-4b33-bcec-be9c9010e7fc}')!
MDLLogo comment: 'Description--------------------I am a brush to create a MDL logo.'!
!MDLLogo categoriesForClass!Material-Design-Lite-Components-Footer! !
!MDLLogo methodsFor!

initialize	super initialize.	self class: 'mdl-logo'! !
!MDLLogo categoriesFor: #initialize!initialization!public! !

