"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLLayoutIcon
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLLayoutIcon guid: (GUID fromString: '{5477a579-f0e2-4aa5-9181-bbb5ba59e93b}')!
MDLLayoutIcon comment: 'IDescription--------------------I am a brush to create an icon for mdl layouts.'!
!MDLLayoutIcon categoriesForClass!Material-Design-Lite-Components-Layout! !
!MDLLayoutIcon methodsFor!

initialize	super initialize.	self class: 'mdl-layout-icon'! !
!MDLLayoutIcon categoriesFor: #initialize!initialization!public! !

