"Filed out from Dolphin Smalltalk 7"!

MDLAbstractPanelResizer subclass: #MDLLeftPanelResizer
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLLeftPanelResizer guid: (GUID fromString: '{07a1d0a7-ffa8-4278-86a2-d5772067fa1d}')!
MDLLeftPanelResizer comment: 'Description--------------------I am a simple component allowing to resize a panel to the left of the window. '!
!MDLLeftPanelResizer categoriesForClass!Material-Design-Lite-Extensions-Panels! !
!MDLLeftPanelResizer methodsFor!

initMethodName	^ 'initLeftResizer()'!

panelClass	^ #'resizer-left'! !
!MDLLeftPanelResizer categoriesFor: #initMethodName!accessing!public! !
!MDLLeftPanelResizer categoriesFor: #panelClass!accessing!public! !

