"Filed out from Dolphin Smalltalk 7"!

MDLAbstractFooterLinksList subclass: #MDLMiniFooterLinksList
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLMiniFooterLinksList guid: (GUID fromString: '{de0ca5cf-9e41-4ce4-bf19-855522bf9842}')!
MDLMiniFooterLinksList comment: ''!
!MDLMiniFooterLinksList categoriesForClass!Material-Design-Lite-Widgets-Footer! !
!MDLMiniFooterLinksList methodsFor!

renderLinksListOn: html	html mdlMiniFooterLinkList: [ 		self renderLinksOn: html ]! !
!MDLMiniFooterLinksList categoriesFor: #renderLinksListOn:!private! !

