"Filed out from Dolphin Smalltalk 7"!

WAButtonTag subclass: #MDLMiniFooterSocialButton
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLMiniFooterSocialButton guid: (GUID fromString: '{db7d112a-6ad0-4965-95c0-6d19d6503467}')!
MDLMiniFooterSocialButton comment: 'Description--------------------I am a brush to create a social button inside a mini footer.Example--------------------	html		mdlMiniFooter: [ html				mdlMiniFooterLeftSection: [ html mdlLogo: ''Title''.					html						mdlMiniFooterLinkList: [ html listItem: [ html anchor: ''Help'' ].							html listItem: [ html anchor: ''Privacy & Terms'' ] ] ] ]'!
!MDLMiniFooterSocialButton categoriesForClass!Material-Design-Lite-Components-Footer! !
!MDLMiniFooterSocialButton methodsFor!

initialize	super initialize.	self class: 'mdl-mini-footer__social-btn'! !
!MDLMiniFooterSocialButton categoriesFor: #initialize!initialization!public! !

