"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLMiniFooterRightSection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLMiniFooterRightSection guid: (GUID fromString: '{043a0107-d2a1-493d-9388-a8df6fcff3f6}')!
MDLMiniFooterRightSection comment: 'Description--------------------I am a brush to create a right section inside a mini footer.Example--------------------	html		mdlMiniFooter: [ html				mdlMiniFooterLeftSection: [ html mdlLogo: ''Title''.					html						mdlMiniFooterLinkList: [ html listItem: [ html anchor: ''Help'' ].							html listItem: [ html anchor: ''Privacy & Terms'' ] ] ] ]'!
!MDLMiniFooterRightSection categoriesForClass!Material-Design-Lite-Components-Footer! !
!MDLMiniFooterRightSection methodsFor!

initialize	super initialize.	self class: 'mdl-mini-footer__right-section'! !
!MDLMiniFooterRightSection categoriesFor: #initialize!initialization!public! !

