"Filed out from Dolphin Smalltalk 7"!

MDLAbstractFooterLinksList subclass: #MDLMegaFooterLinksList
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLMegaFooterLinksList guid: (GUID fromString: '{2a494b08-6eec-4fd7-8460-1158299b1345}')!
MDLMegaFooterLinksList comment: ''!
!MDLMegaFooterLinksList categoriesForClass!Material-Design-Lite-Widgets-Footer! !
!MDLMegaFooterLinksList methodsFor!

renderLinksListOn: html	html mdlFooterLinkList: [ 		self renderLinksOn: html ]! !
!MDLMegaFooterLinksList categoriesFor: #renderLinksListOn:!private! !

