"Filed out from Dolphin Smalltalk 7"!

MDLDivTag subclass: #MDLMiniFooterLeftSection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLMiniFooterLeftSection guid: (GUID fromString: '{d958e088-60ad-444a-ac9d-97128ff33b2e}')!
MDLMiniFooterLeftSection comment: 'Description--------------------I am a brush to create a left section inside a mini footer.Example--------------------	html		mdlMiniFooter: [ html				mdlMiniFooterLeftSection: [ html mdlLogo: ''Title''.					html						mdlMiniFooterLinkList: [ html listItem: [ html anchor: ''Help'' ].							html listItem: [ html anchor: ''Privacy & Terms'' ] ] ] ]'!
!MDLMiniFooterLeftSection categoriesForClass!Material-Design-Lite-Components-Footer! !
!MDLMiniFooterLeftSection methodsFor!

initialize	super initialize.	self class: 'mdl-mini-footer__left-section'! !
!MDLMiniFooterLeftSection categoriesFor: #initialize!initialization!public! !

