"Filed out from Dolphin Smalltalk 7"!

MDLAbstractLayoutSection subclass: #MDLNilLayoutSection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLNilLayoutSection guid: (GUID fromString: '{363b574d-beaf-4f4b-ae50-69d4d3366ae4}')!
MDLNilLayoutSection comment: ''!
!MDLNilLayoutSection categoriesForClass!Material-Design-Lite-Widgets-Header! !
!MDLNilLayoutSection methodsFor!

renderContentOn: html	"do nothing"! !
!MDLNilLayoutSection categoriesFor: #renderContentOn:!private! !

