"Filed out from Dolphin Smalltalk 7"!

MDLAbstractPanelResizer subclass: #MDLRightPanelResizer
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLRightPanelResizer guid: (GUID fromString: '{ad8ef249-1c94-4fb3-9fc0-331d126909f4}')!
MDLRightPanelResizer comment: 'Description--------------------I am a simple component allowing to resize a panel to the right of the window. '!
!MDLRightPanelResizer categoriesForClass!Material-Design-Lite-Extensions-Panels! !
!MDLRightPanelResizer methodsFor!

initMethodName	^ 'initRightResizer()'!

panelClass	^ #'resizer-right'! !
!MDLRightPanelResizer categoriesFor: #initMethodName!accessing!public! !
!MDLRightPanelResizer categoriesFor: #panelClass!accessing!public! !

