"Filed out from Dolphin Smalltalk 7"!

WAComponent subclass: #MDLScreen
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLScreen guid: (GUID fromString: '{ee0c64b3-8a3c-4bff-8883-9d8c70f5aa25}')!
MDLScreen comment: 'WADecoration subclass: #MDLScreenFooter	instanceVariableNames: ''footer''	classVariableNames: ''''	package: ''Material-Design-Lite-Core'''!
!MDLScreen categoriesForClass!Material-Design-Lite-Core! !
