"Filed out from Dolphin Smalltalk 7"!

MDLSortableTableHeader subclass: #MDLSortableTableHeaderNumeric
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLSortableTableHeaderNumeric guid: (GUID fromString: '{41ef77e3-e195-4579-a42a-5ac8edbe66b2}')!
MDLSortableTableHeaderNumeric comment: ''!
!MDLSortableTableHeaderNumeric categoriesForClass!Material-Design-Lite-Widgets-Table! !
!MDLSortableTableHeaderNumeric methodsFor!

headingCellOn: html	^ html mdlTableHeading		style: 'cursor: pointer;';		yourself!

tableCellOn: html	^ html mdlTableCell! !
!MDLSortableTableHeaderNumeric categoriesFor: #headingCellOn:!public!rendering! !
!MDLSortableTableHeaderNumeric categoriesFor: #tableCellOn:!public!rendering! !

