"Filed out from Dolphin Smalltalk 7"!

MDLAbstractFilter subclass: #MDLSubstringFilter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLSubstringFilter guid: (GUID fromString: '{5b7d5191-6afa-499f-ad8a-3e920e761f8c}')!
MDLSubstringFilter comment: 'MDLSubstringFilter class	instanceVariableNames: '''''!
!MDLSubstringFilter categoriesForClass!Material-Design-Lite-Widgets-List! !
!MDLSubstringFilter class methodsFor!

formatedElement: aString matches: aPattern	^ aString includesSubstring: aPattern! !
!MDLSubstringFilter class categoriesFor: #formatedElement:matches:!accessing!public! !

