"Filed out from Dolphin Smalltalk 7"!

WALabelTag subclass: #MDLTextFieldLabel
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLTextFieldLabel guid: (GUID fromString: '{1a097e5b-791c-43d2-83bd-af298296b8e3}')!
MDLTextFieldLabel comment: 'Description--------------------I am a brush to create a textField label.Example--------------------	html		mdlTextFieldContainer: [ html mdlTextFieldLabel				for: html nextId;				with: ''Text...''.			html mdlTextFieldInput id: html lastId ]'!
!MDLTextFieldLabel categoriesForClass!Material-Design-Lite-Components-Forms! !
!MDLTextFieldLabel methodsFor!

initialize	super initialize.	self class: 'mdl-textfield__label'! !
!MDLTextFieldLabel categoriesFor: #initialize!initialization!public! !

