"Filed out from Dolphin Smalltalk 7"!

MDLDemoScreen subclass: #MDLWidgetDemo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLWidgetDemo guid: (GUID fromString: '{9a74ddfd-97ef-427b-9e80-d59041261523}')!
MDLWidgetDemo comment: 'MDLWidgetDemo subclass: #MDLCalendarScreen	instanceVariableNames: ''selectedDay''	classVariableNames: ''''	poolDictionaries: ''''	category: ''Material-Design-Lite-Demo-Widgets'''!
!MDLWidgetDemo categoriesForClass!Material-Design-Lite-Demo-Widgets! !
