"Filed out from Dolphin Smalltalk 7"!

MDLDemoScreen subclass: #MDLWidgetDemo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
MDLWidgetDemo guid: (GUID fromString: '{9a74ddfd-97ef-427b-9e80-d59041261523}')!
MDLWidgetDemo comment: 'MDLWidgetDemo class	instanceVariableNames: '''''!
!MDLWidgetDemo categoriesForClass!Material-Design-Lite-Demo-Widgets! !
!MDLWidgetDemo class methodsFor!

isAbstract	^ self = MDLWidgetDemo! !
!MDLWidgetDemo class categoriesFor: #isAbstract!public!testing! !

